# Generated by Django 5.1.8 on 2025-04-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_tentativa', models.DateTimeField(auto_now_add=True)),
                ('bl_sucesso', models.BooleanField(default=False)),
                ('id_usuario_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tentativasAcesso', to='usuarios_empresas.usuarioempresa', verbose_name='UsuarioEmpresa')),
            ],
            options={
                'verbose_name': 'Tentativa de Acesso',
                'verbose_name_plural': 'Tentativas de Acesso',
                'db_table': 'tb_tentativa_acesso',
            },
        ),
    ]
