# Generated by Django 5.1.8 on 2025-04-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaAcessoAnonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_tentativa', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tentativasAcessoAnonimos', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tentativa Acesso Anonimo',
                'verbose_name_plural': 'Tentativas de Acesso Anonimo',
                'db_table': 'tb_tentativa_acesso_anonimo',
            },
        ),
    ]
