# Generated by Django 5.1.8 on 2025-04-07 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tp_alerta', models.CharField(max_length=50)),
                ('ds_mensagem', models.JSONField()),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'tb_alerta',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_nome', models.CharField(max_length=100)),
                ('ds_cnpj', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'tb_empresa',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nu_cep', models.CharField(max_length=9)),
                ('nm_logradouro', models.CharField(max_length=100)),
                ('nu_numero', models.CharField(max_length=20)),
                ('ds_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('nm_bairro', models.CharField(max_length=50)),
                ('nm_cidade', models.CharField(max_length=50)),
                ('sg_estado', models.CharField(max_length=2)),
                ('nm_pais', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'tb_endereco',
                'ordering': ['nm_pais', 'nm_cidade', 'sg_estado', 'nm_bairro', 'nm_logradouro'],
            },
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Face',
                'verbose_name_plural': 'Faces',
                'db_table': 'tb_face',
            },
        ),
        migrations.CreateModel(
            name='FaceAnonima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Face Anonimas',
                'verbose_name_plural': 'Faces Anonimas',
                'db_table': 'tb_face_anonima',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tp_relatorio', models.CharField(max_length=50)),
                ('js_conteudo', models.JSONField()),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relatorio',
                'verbose_name_plural': 'Relatorios',
                'db_table': 'tb_relatorio',
            },
        ),
        migrations.CreateModel(
            name='TentativaAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_tentativa', models.DateTimeField(auto_now_add=True)),
                ('bl_sucesso', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tentativa de Acesso',
                'verbose_name_plural': 'Tentativas de Acesso',
                'db_table': 'tb_tentativa_acesso',
            },
        ),
        migrations.CreateModel(
            name='TentativaAcessoAnonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_tentativa', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tentativa Acesso Anonimo',
                'verbose_name_plural': 'Tentativas de Acesso Anonimo',
                'db_table': 'tb_tentativa_acesso_anonimo',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_nome', models.CharField(max_length=100)),
                ('ds_email', models.EmailField(max_length=254, unique=True)),
                ('nu_telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('nu_cpf', models.CharField(max_length=15)),
                ('ds_senha_hash', models.CharField(max_length=200)),
                ('bl_bloqueado', models.BooleanField(default=False)),
                ('nu_tentativas_falhas', models.IntegerField()),
                ('dt_bloqueio', models.DateTimeField(blank=True, null=True)),
                ('id_endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='app.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'tb_usuario',
                'ordering': ['nm_nome'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds_usuario_permissao', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='app.endereco', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='id_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='app.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='tentativaacessoanonimo',
            name='id_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tentativasAcessoAnonimos', to='app.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='faceanonima',
            name='id_tentativa_acesso_anonimo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facesanonimas', to='app.tentativaacessoanonimo', verbose_name='Tentativa de Acesso Anonimo'),
        ),
        migrations.AddField(
            model_name='face',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='app.usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosempresas', to='app.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='usuarioempresa',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosempresa', to='app.usuario', verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='tentativaacesso',
            name='id_usuario_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tentativasAcesso', to='app.usuarioempresa', verbose_name='UsuarioEmpresa'),
        ),
        migrations.AddField(
            model_name='alerta',
            name='id_usuario_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='app.usuarioempresa', verbose_name='UsuarioEmpresa'),
        ),
    ]
