# Generated by Django 5.1.8 on 2025-04-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_nome', models.CharField(max_length=100)),
                ('ds_cnpj', models.CharField(max_length=20)),
                ('id_endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='enderecos.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'tb_empresa',
            },
        ),
    ]
