# Generated by Django 5.1.8 on 2025-04-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='ds_senha_hash',
            field=models.CharField(default='', max_length=20),
        ),
    ]
