# Generated by Django 5.1.8 on 2025-04-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ds_usuario_permissao', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosempresas', to='empresas.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosempresa', to='usuarios.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
