# Generated by Django 5.1.8 on 2025-04-23 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tentativas_acesso_anonimo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAnonima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_anonimo', models.ImageField(upload_to='img_anonimas/')),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
                ('id_tentativa_acesso_anonimo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facesanonimas', to='tentativas_acesso_anonimo.tentativaacessoanonimo', verbose_name='Tentativa de Acesso Anonimo')),
            ],
            options={
                'verbose_name': 'Face Anonimas',
                'verbose_name_plural': 'Faces Anonimas',
                'db_table': 'tb_face_anonima',
            },
        ),
    ]
