# Generated by Django 5.1.8 on 2025-04-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nu_cep', models.CharField(max_length=9)),
                ('nm_logradouro', models.CharField(max_length=100)),
                ('nu_numero', models.CharField(max_length=20)),
                ('ds_complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('nm_bairro', models.CharField(max_length=50)),
                ('nm_cidade', models.CharField(max_length=50)),
                ('sg_estado', models.CharField(max_length=2)),
                ('nm_pais', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'tb_endereco',
                'ordering': ['nm_pais', 'nm_cidade', 'sg_estado', 'nm_bairro', 'nm_logradouro'],
            },
        ),
    ]
