# Generated by Django 5.1.8 on 2025-04-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_nome', models.CharField(max_length=100)),
                ('ds_email', models.EmailField(max_length=254, unique=True)),
                ('nu_telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('nu_cpf', models.CharField(max_length=15)),
                ('ds_senha_hash', models.CharField(max_length=200)),
                ('bl_bloqueado', models.BooleanField(default=False)),
                ('nu_tentativas_falhas', models.IntegerField()),
                ('dt_bloqueio', models.DateTimeField(blank=True, null=True)),
                ('id_endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='enderecos.endereco', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'tb_usuario',
                'ordering': ['nm_nome'],
            },
        ),
    ]
