# Generated by Django 5.1.8 on 2025-04-28 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_ds_senha_hash'),
        ('usuarios', '0002_usuario_cd_recuperacao_senha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_login', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logins', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Login de Usuário',
                'verbose_name_plural': 'Logins de Usuários',
                'db_table': 'tb_login_usuario',
            },
        ),
    ]
