# Generated by Django 5.1.8 on 2025-04-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios_empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tp_alerta', models.CharField(max_length=50)),
                ('js_mensagem', models.JSONField()),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='usuarios_empresas.usuarioempresa', verbose_name='UsuarioEmpresa')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'tb_alerta',
            },
        ),
    ]
