# Generated by Django 5.1.8 on 2025-04-23 19:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arr_imagem', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Face',
                'verbose_name_plural': 'Faces',
                'db_table': 'tb_face',
            },
        ),
    ]
