# Generated by Django 5.1.8 on 2025-04-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAnonimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp_alerta', models.CharField(max_length=50)),
                ('js_mensagem', models.JSONField()),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertasAnonimos', to='empresas.empresa', verbose_name='Alerta de Acesso Anônimo')),
            ],
            options={
                'verbose_name': 'Alerta Anônimo',
                'verbose_name_plural': 'Alertas Anônimos',
                'db_table': 'tb_alerta_anonimo',
            },
        ),
    ]
