# Generated by Django 5.1.8 on 2025-04-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas_anonimos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertaanonimo',
            old_name='id_usuario_empresa',
            new_name='id_empresa',
        ),
    ]
