# Generated by Django 5.1.8 on 2025-04-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tp_relatorio', models.CharField(max_length=50)),
                ('js_conteudo', models.JSONField()),
                ('dt_criado', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Relatorio',
                'verbose_name_plural': 'Relatorios',
                'db_table': 'tb_relatorio',
            },
        ),
    ]
